baseURL = 'https://gwenodiving.github.io/'
languageCode = 'en-us'
title = 'Gweno Salomé Diving Taiwan'
theme = "ananke"

[languages]
  [languages.en]
    weight = 1
    languageCode = 'en-us'
    contentDir = "content/en"
    languageName = 'English'
  [languages.fr]
    weight = 2
    languageCode = 'fr-fr'
    contentDir = "content/fr"
    languageName = 'Français'
  [languages.zh]
    weight = 3
    languageCode = 'zh-tw'
    contentDir = "content/zh"
    languageName = '中文'
