baseURL = 'https://gwenodiving.github.io/'
languageCode = 'en-us'
title = 'Gweno Salomé Diving Taiwan'
theme = "ananke"

SectionPagesMenu = "main"

# Allow raw html
[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    weight = 1
    languageCode = 'en-us'
    languageName = 'English'
  [languages.fr]
    weight = 2
    languageCode = 'fr-fr'
    languageName = 'Français'
  [languages.zh]
    weight = 3
    languageCode = 'zh-tw'
    languageName = '中文'

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    identifier = "padi_level"
    name = "PADI Levels"
    url = "/padi_levels"
    weight = 2
    parent = "Home"

[[params.ananke_socials]]
  name = 'instagram'
  url = 'https://www.instagram.com/gweno_diving_taiwan/'

[[params.ananke_socials]]
  name = 'facebook'
  url = 'https://www.facebook.com/profile.php?id=61550060433253'

[params]
  line = 'gweno16'
