baseURL = 'https://gwenodiving.github.io/'
languageCode = 'en-us'
title = 'Gweno Salomé Diving Taiwan'
theme = "ananke"

SectionPagesMenu = "main"

# Allow raw html
[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
    weight = 1
    languageCode = 'en-us'
    contentDir = "content/en"
    languageName = 'English'
  [languages.fr]
    weight = 2
    languageCode = 'fr-fr'
    contentDir = "content/fr"
    languageName = 'Français'
  [languages.zh]
    weight = 3
    languageCode = 'zh-tw'
    contentDir = "content/zh"
    languageName = '中文'

[[params.ananke_socials]]
  name = 'instagram'
  url = 'https://www.instagram.com/gweno_diving_taiwan/'

[[params.ananke_socials]]
  name = 'facebook'
  url = 'https://m.facebook.com/100089367170168'

[params]
  line = 'gweno16'
